// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsccydbevercskzyyzuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzY2N5ZGJldmVyY3Nrenl5enVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjc2NDksImV4cCI6MjA2NTgwMzY0OX0.nxY1c2sWbvCmBy9AEvTvOehcwVHhHTxhd9AxyK59-90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);